name: Publish to NPM

on:
  workflow_run:
    workflows: ["Reversion"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: npm ci
      
      # - name: Build package
            #   run: npm run build
      - name: Debug npm configuration
        run: |
          echo "NPM config:"
          npm config list
          echo "Content of ~/.npmrc:"
          cat ~/.npmrc || echo "No ~/.npmrc file"
          echo "Testing authentication:"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami || echo "Authentication failed"
          
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public